// This file is generated by scripts/icons.ts
// Do not edit this file manually

import { SVGComponent } from '@/types'

import AntDesignZhihuOutlined from '@/assets/icons/ant-design/zhihu-outlined.svg'
import GrommetIconsGithub from '@/assets/icons/grommet-icons/github.svg'
import HeroiconsRssSolid from '@/assets/icons/heroicons/rss-solid.svg'
import LogosNextjs from '@/assets/icons/logos/nextjs.svg'
import MingcuteMailFill from '@/assets/icons/mingcute/mail-fill.svg'
import PhMoonFill from '@/assets/icons/ph/moon-fill.svg'
import PhSunDuotone from '@/assets/icons/ph/sun-duotone.svg'
import RiCreativeCommonsLine from '@/assets/icons/ri/creative-commons-line.svg'
import SimpleIconsJuejin from '@/assets/icons/simple-icons/juejin.svg'
import SkillIconsNextjsDark from '@/assets/icons/skill-icons/nextjs-dark.svg'
import SkillIconsNextjsLight from '@/assets/icons/skill-icons/nextjs-light.svg'
import SkillIconsNodejsDark from '@/assets/icons/skill-icons/nodejs-dark.svg'
import SkillIconsNodejsLight from '@/assets/icons/skill-icons/nodejs-light.svg'
import SkillIconsReactDark from '@/assets/icons/skill-icons/react-dark.svg'
import SkillIconsReactLight from '@/assets/icons/skill-icons/react-light.svg'
import SkillIconsStyledcomponents from '@/assets/icons/skill-icons/styledcomponents.svg'
import SkillIconsTailwindcssDark from '@/assets/icons/skill-icons/tailwindcss-dark.svg'
import SkillIconsTailwindcssLight from '@/assets/icons/skill-icons/tailwindcss-light.svg'
import SkillIconsTypescript from '@/assets/icons/skill-icons/typescript.svg'

export const LOCAL_ICONS: Record<string, SVGComponent> = {
  'ant-design:zhihu-outlined': AntDesignZhihuOutlined,
  'grommet-icons:github': GrommetIconsGithub,
  'heroicons:rss-solid': HeroiconsRssSolid,
  'logos:nextjs': LogosNextjs,
  'mingcute:mail-fill': MingcuteMailFill,
  'ph:moon-fill': PhMoonFill,
  'ph:sun-duotone': PhSunDuotone,
  'ri:creative-commons-line': RiCreativeCommonsLine,
  'simple-icons:juejin': SimpleIconsJuejin,
  'skill-icons:nextjs-dark': SkillIconsNextjsDark,
  'skill-icons:nextjs-light': SkillIconsNextjsLight,
  'skill-icons:nodejs-dark': SkillIconsNodejsDark,
  'skill-icons:nodejs-light': SkillIconsNodejsLight,
  'skill-icons:react-dark': SkillIconsReactDark,
  'skill-icons:react-light': SkillIconsReactLight,
  'skill-icons:styledcomponents': SkillIconsStyledcomponents,
  'skill-icons:tailwindcss-dark': SkillIconsTailwindcssDark,
  'skill-icons:tailwindcss-light': SkillIconsTailwindcssLight,
  'skill-icons:typescript': SkillIconsTypescript,
}
